version: "3.9"
services:
  efspjava:
    build:
      context: .
    # Necessary b/c docassemble is external to the docker network
    ports:
      - target: 9009
        published: 80
      - target: 9000
        published: 443
    env_file: .env
    depends_on:
      - "db"
    volumes:
      - type: bind
        source: ./src/main/config
        target: /tmp/tls_certs
    deploy:
      resources:
        limits:
          memory: 4G
    # Uncomment this for debugging: you can get exact SOAP envelopes being
    # sent by running wireshark locally
    #  - type: bind
    #    source: .
    #    target: /tmp/secrets
  db:
    image: "postgres:14"
    shm_size: 128m
    env_file: .env
    volumes:
      - data-volume:/var/lib/postgresql/data
      - ./postgres-config:/etc/postgresql

volumes:
  data-volume:
