version: "3.9"
services:
  efspjava:
    build:
      context: .
      args: 
        EFM_SUPPORT: tyler
    # Necessary b/c docassemble is external to the docker network
    ports:
      - "9000:9000"
    env_file: .env
    depends_on:
      - "db"
  db:
    image: "postgres:14"
    env_file: .env
    volumes:
      - data-volume:/var/lib/postgresql/data

volumes:
  data-volume:
