version: "3.9"
services:
  efspjava:
    build:
      context: .
      args: 
        EFM_SUPPORT: tyler
    # Necessary b/c docassemble is external to the docker network
    ports:
      - "9000:9000"
    env_file: .env
    depends_on:
      - "db"
    # Use to get exact SOAP envelopes being sent, you can run wireshark locally
    #volumes:
    #  - .:/tmp/secrets
  db:
    image: "postgres:14"
    shm_size: 128MB
    env_file: .env
    volumes:
      - data-volume:/var/lib/postgresql/data

volumes:
  data-volume:
